# Generated by Django 3.2.9 on 2021-11-28 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.DateTimeField(default=datetime.datetime(2021, 11, 28, 20, 42, 4, 210630))),
                ('token', models.UUIDField()),
            ],
        ),
    ]
