# Generated by Django 3.2.9 on 2021-11-29 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationserver', '0002_posttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 22, 33, 37, 548435)),
        ),
        migrations.AlterField(
            model_name='posttoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
