# Generated by Django 3.2.9 on 2021-11-29 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationserver', '0003_auto_20211129_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 22, 34, 8, 743052)),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
