# Generated by Django 3.2.9 on 2021-11-29 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationserver', '0004_auto_20211129_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='posttoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 22, 40, 40, 640387)),
        ),
    ]
