# Generated by Django 3.2.9 on 2021-12-09 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationserver', '0005_auto_20211129_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 16, 6, 33, 384402)),
        ),
    ]
