# Generated by Django 3.2.9 on 2021-12-10 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20211210_1813'),
        ('authorizationserver', '0006_alter_posttoken_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_blog',
            field=models.ManyToManyField(to='blogs.Blog'),
        ),
        migrations.AlterField(
            model_name='posttoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 18, 43, 47, 610520)),
        ),
    ]
