# Generated by Django 4.0 on 2021-12-13 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationserver', '0008_auto_20211210_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 23, 36, 6, 790967)),
        ),
    ]
