# Generated by Django 4.0 on 2021-12-14 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationserver', '0009_alter_posttoken_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 14, 14, 30, 248222)),
        ),
    ]
