# Generated by Django 4.0 on 2021-12-29 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationserver', '0010_alter_posttoken_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 13, 8, 44, 307563)),
        ),
    ]
