# Generated by Django 4.0 on 2022-01-12 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationserver', '0011_alter_posttoken_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AlterField(
            model_name='posttoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 23, 25, 9, 522968)),
        ),
    ]
