# Generated by Django 4.0 on 2022-01-16 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationserver', '0013_alter_posttoken_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 15, 46, 15, 272609)),
        ),
    ]
